# Generated by Django 5.0.6 on 2024-11-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
