# Generated by Django 5.0.6 on 2024-12-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_category_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answer_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions_images/'),
        ),
    ]
