# Generated by Django 5.0.6 on 2024-11-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_signuptoken_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
